// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(MovieApplicationContext))]
    [Migration("20220127062433_Initial3entries")]
    partial class Initial3entries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Category = "Action/Adventure",
                            Director = "Anthony Russo, Joe Russo",
                            Edited = false,
                            LentTo = "",
                            Notes = "My wife love it too",
                            Rating = "PG-13",
                            Title = "Infinity War",
                            Year = 2018
                        },
                        new
                        {
                            id = 2,
                            Category = "Action/Adventure",
                            Director = "Phil Lord, Christopher Miller",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "Lego Move, The",
                            Year = 2014
                        },
                        new
                        {
                            id = 3,
                            Category = "Rom-Com",
                            Director = "Nora Ephron",
                            Edited = false,
                            LentTo = "",
                            Notes = "My wife's pick",
                            Rating = "PG",
                            Title = "Sleepless in Seattle",
                            Year = 1993
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
